# Generated by Django 3.2.5 on 2021-07-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancestests',
            name='process_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
